-- CreateTable
CREATE TABLE `Popup` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NULL,
    `content` TEXT NOT NULL,
    `type` ENUM('EXIT_INTENT', 'TIMED', 'SCROLL_BASED', 'PAGE_LOAD', 'CLICK_TRIGGER') NOT NULL DEFAULT 'EXIT_INTENT',
    `triggerValue` INTEGER NULL,
    `target` ENUM('ALL_PAGES', 'HOMEPAGE', 'PRODUCT_PAGES', 'CART_PAGE', 'CHECKOUT', 'BLOG', 'CUSTOM_URL') NOT NULL DEFAULT 'ALL_PAGES',
    `customUrls` TEXT NULL,
    `position` ENUM('CENTER', 'TOP', 'BOTTOM', 'TOP_LEFT', 'TOP_RIGHT', 'BOTTOM_LEFT', 'BOTTOM_RIGHT') NOT NULL DEFAULT 'CENTER',
    `width` INTEGER NOT NULL DEFAULT 500,
    `height` INTEGER NULL,
    `backgroundColor` VARCHAR(191) NOT NULL DEFAULT '#ffffff',
    `textColor` VARCHAR(191) NOT NULL DEFAULT '#000000',
    `buttonText` VARCHAR(191) NOT NULL DEFAULT 'Get Offer',
    `buttonColor` VARCHAR(191) NOT NULL DEFAULT '#000000',
    `buttonTextColor` VARCHAR(191) NOT NULL DEFAULT '#ffffff',
    `showCloseButton` BOOLEAN NOT NULL DEFAULT true,
    `overlayColor` VARCHAR(191) NOT NULL DEFAULT 'rgba(0,0,0,0.5)',
    `imageUrl` VARCHAR(191) NULL,
    `frequency` VARCHAR(191) NOT NULL DEFAULT 'once_per_session',
    `delaySeconds` INTEGER NOT NULL DEFAULT 0,
    `ctaType` VARCHAR(191) NOT NULL DEFAULT 'link',
    `ctaUrl` VARCHAR(191) NULL,
    `discountCode` VARCHAR(191) NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT false,
    `startDate` DATETIME(3) NULL,
    `endDate` DATETIME(3) NULL,
    `priority` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `Popup_isActive_idx`(`isActive`),
    INDEX `Popup_type_idx`(`type`),
    INDEX `Popup_target_idx`(`target`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
