-- CreateTable
CREATE TABLE `InvoiceSettings` (
    `id` VARCHAR(191) NOT NULL,
    `invoiceNumberPrefix` VARCHAR(191) NOT NULL DEFAULT 'INV',
    `invoiceNumberFormat` VARCHAR(191) NOT NULL DEFAULT '{{prefix}}-{{number}}',
    `nextInvoiceNumber` INTEGER NOT NULL DEFAULT 1,
    `defaultTerms` TEXT NULL,
    `defaultNotes` TEXT NULL,
    `defaultDueDays` INTEGER NOT NULL DEFAULT 30,
    `logoUrl` VARCHAR(191) NULL,
    `companyName` VARCHAR(191) NULL,
    `companyAddress` TEXT NULL,
    `companyPhone` VARCHAR(191) NULL,
    `companyEmail` VARCHAR(191) NULL,
    `companyWebsite` VARCHAR(191) NULL,
    `companyTaxId` VARCHAR(191) NULL,
    `primaryColor` VARCHAR(191) NOT NULL DEFAULT '#000000',
    `secondaryColor` VARCHAR(191) NOT NULL DEFAULT '#666666',
    `accentColor` VARCHAR(191) NOT NULL DEFAULT '#3182ce',
    `fontFamily` VARCHAR(191) NOT NULL DEFAULT 'Helvetica',
    `fontSize` INTEGER NOT NULL DEFAULT 10,
    `defaultTemplateId` VARCHAR(191) NULL,
    `emailSubjectTemplate` VARCHAR(191) NULL DEFAULT 'Invoice {{invoiceNumber}} from {{companyName}}',
    `emailBodyTemplate` TEXT NULL,
    `autoSendOnCreate` BOOLEAN NOT NULL DEFAULT false,
    `sendCopyToAdmin` BOOLEAN NOT NULL DEFAULT false,
    `adminEmail` VARCHAR(191) NULL,
    `defaultTaxRate` DECIMAL(5, 2) NULL,
    `taxLabel` VARCHAR(191) NOT NULL DEFAULT 'Tax',
    `showTaxBreakdown` BOOLEAN NOT NULL DEFAULT true,
    `currency` VARCHAR(191) NOT NULL DEFAULT 'USD',
    `currencySymbol` VARCHAR(191) NOT NULL DEFAULT '$',
    `paymentMethods` JSON NULL,
    `showPaymentLink` BOOLEAN NOT NULL DEFAULT true,
    `paymentGateway` VARCHAR(191) NULL,
    `showQRCode` BOOLEAN NOT NULL DEFAULT false,
    `enableSignatures` BOOLEAN NOT NULL DEFAULT false,
    `customFields` JSON NULL,
    `multiLanguage` BOOLEAN NOT NULL DEFAULT false,
    `defaultLanguage` VARCHAR(191) NOT NULL DEFAULT 'en',
    `headerText` TEXT NULL,
    `footerText` TEXT NULL,
    `showFooter` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `InvoiceSettings_id_key`(`id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
