-- CreateTable
CREATE TABLE `checkout_settings` (
    `id` VARCHAR(191) NOT NULL,
    `showPhone` BOOLEAN NOT NULL DEFAULT true,
    `showCompany` BOOLEAN NOT NULL DEFAULT false,
    `showAddressLine2` BOOLEAN NOT NULL DEFAULT true,
    `requirePhone` BOOLEAN NOT NULL DEFAULT false,
    `thankYouMessage` TEXT NULL,
    `checkoutBanner` TEXT NULL,
    `checkoutBannerType` VARCHAR(191) NULL,
    `enableGuestCheckout` BOOLEAN NOT NULL DEFAULT true,
    `enableOrderNotes` BOOLEAN NOT NULL DEFAULT true,
    `orderNotesLabel` VARCHAR(191) NULL,
    `freeShippingThreshold` DECIMAL(10, 2) NULL,
    `defaultShippingCost` DECIMAL(10, 2) NOT NULL DEFAULT 10,
    `logoUrl` VARCHAR(191) NULL,
    `primaryColor` VARCHAR(191) NULL DEFAULT '#000000',
    `secondaryColor` VARCHAR(191) NULL DEFAULT '#666666',
    `buttonStyle` VARCHAR(191) NULL DEFAULT 'rounded',
    `fontFamily` VARCHAR(191) NULL DEFAULT 'system',
    `pageWidth` VARCHAR(191) NULL DEFAULT 'normal',
    `checkoutLayout` VARCHAR(191) NULL DEFAULT 'single',
    `progressStyle` VARCHAR(191) NULL DEFAULT 'steps',
    `orderSummaryPosition` VARCHAR(191) NULL DEFAULT 'right',
    `fieldLabels` JSON NULL,
    `fieldPlaceholders` JSON NULL,
    `fieldOrder` JSON NULL,
    `showDeliveryInstructions` BOOLEAN NOT NULL DEFAULT false,
    `deliveryInstructionsLabel` VARCHAR(191) NULL,
    `showAlternativePhone` BOOLEAN NOT NULL DEFAULT false,
    `showGiftMessage` BOOLEAN NOT NULL DEFAULT false,
    `giftMessageLabel` VARCHAR(191) NULL,
    `showDeliveryDate` BOOLEAN NOT NULL DEFAULT false,
    `customFields` JSON NULL,
    `trustBadges` JSON NULL,
    `showSecuritySeals` BOOLEAN NOT NULL DEFAULT true,
    `moneyBackGuarantee` TEXT NULL,
    `customerServiceDisplay` BOOLEAN NOT NULL DEFAULT false,
    `customerServiceText` TEXT NULL,
    `customerServicePhone` VARCHAR(191) NULL,
    `customerServiceEmail` VARCHAR(191) NULL,
    `showOrderCount` BOOLEAN NOT NULL DEFAULT false,
    `orderCountText` VARCHAR(191) NULL,
    `showRecentPurchases` BOOLEAN NOT NULL DEFAULT false,
    `recentPurchaseDelay` INTEGER NULL DEFAULT 5000,
    `showTestimonials` BOOLEAN NOT NULL DEFAULT false,
    `testimonials` JSON NULL,
    `showTrustRating` BOOLEAN NOT NULL DEFAULT false,
    `trustRatingScore` DECIMAL(2, 1) NULL,
    `trustRatingCount` INTEGER NULL,
    `promotionalBanners` JSON NULL,
    `showCountdownTimer` BOOLEAN NOT NULL DEFAULT false,
    `countdownEndDate` DATETIME(3) NULL,
    `countdownText` VARCHAR(191) NULL,
    `showFreeShippingBar` BOOLEAN NOT NULL DEFAULT false,
    `freeShippingBarText` VARCHAR(191) NULL,
    `showUpsells` BOOLEAN NOT NULL DEFAULT false,
    `upsellProducts` JSON NULL,
    `upsellTitle` VARCHAR(191) NULL,
    `upsellPosition` VARCHAR(191) NULL DEFAULT 'cart',
    `showLowStock` BOOLEAN NOT NULL DEFAULT false,
    `lowStockThreshold` INTEGER NULL DEFAULT 5,
    `lowStockText` VARCHAR(191) NULL,
    `scarcityMessage` TEXT NULL,
    `urgencyBadgeStyle` VARCHAR(191) NULL DEFAULT 'warning',
    `discountFieldPosition` VARCHAR(191) NULL DEFAULT 'top',
    `showLoyaltyPoints` BOOLEAN NOT NULL DEFAULT false,
    `loyaltyPointsText` VARCHAR(191) NULL,
    `showGiftWithPurchase` BOOLEAN NOT NULL DEFAULT false,
    `giftThreshold` DECIMAL(10, 2) NULL,
    `giftDescription` TEXT NULL,
    `referralDiscountEnabled` BOOLEAN NOT NULL DEFAULT false,
    `referralDiscountText` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
